name: Deploy to Github Pages
on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy Application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@main
            - name: Create Node Environment
              uses: actions/setup-node@v1
              with: 
                node-version: 14.x
            - name: Install Packages and Build Application
              run: |
                npm install
                npm run build
            - name: Deploy
              uses: s0/git-publish-subdir-action@master
              env:
                REPO: self
                BRANCH: gh-pages
                FOLDER: dist
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}